### ISSUE TITLE
Instalation Dependency Issue

### ISSUE THREAD

**Issue by alexvcasillas** [mhaagens/nextpresso#1]
Hi there, @mhaagens !

As I told you last night, I'm trying *nextpresso* but I'm having a issue with a dependency when I try to install it globally. Here's the NPM log I got when I try to `npm i -g nextpresso` obviously with sudo and my password properly written 😅 

```
2463 verbose pkgid get-cursor-position@1.0.3
2464 verbose cwd /Users/alexcasillas
2465 verbose Darwin 17.2.0
2466 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "nextpresso" "-g"
2467 verbose node v8.2.1
2468 verbose npm  v5.5.1
2469 error code ELIFECYCLE
2470 error errno 1
2471 error get-cursor-position@1.0.3 install: `node-gyp rebuild`
2471 error Exit status 1
2472 error Failed at the get-cursor-position@1.0.3 install script.
2472 error This is probably not a problem with npm. There is likely additional logging outp$
2473 verbose exit [ 1, true ]
```
Did you test the installation with both Yarn and NPM? Because I'm find this pretty weird.

Hope to hear from you so I could colaborate to this proyect :)

**Comment by mhaagens** [comment]
Thanks for opening the issue! Fixed now, for anyone having trouble just run npm update -g nextpresso (or yarn global upgrade nextpresso).

**Comment by alexvcasillas** [comment]
This issue doesn't finish the installation, with NPM at least doesn't even install it so you need to `npm i -g nextpresso` again instead of updating it : )
